Разметка и графика
htmlacademy-htmlcss/841461-technomart-31 pull request #2
Opened 2021-05-27 15:32 UTC by Gerda0283

1-ая попытка здачи второго д/з (разметка index.html). Плюс обработка графического материала из 3-го д/з без favicon

2021-05-27 18:54 UTC, Shramkoweb requested changes

2021-05-27 18:54 UTC, Shramkoweb commented on blanc.html
> +  </html>
Проверь плагин `editorconfig` у тебя он не установлен.

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +<!DOCTYPE html>
Что делает каталог в ПР - по заданию просят верстку главной. 
2. Разметка главной страницы

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +            <input type="submit" value="Искать"><!--Скрытая-->
Что искать?)

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +          <a class="bookmarks" href="blanc.html">Закладки:</a> <output for="bookmarks" name="result">0</output>
`<output for="bookmarks" name="result">0</output>` обьясни как работает?)

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +          <a class="cart" href="blanc.html">Корзина:</a> <output for="cart" name="result">0</output>
`<output for="cart" name="result">0</output> `аналогично)

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +        <div class="navbar-2">
navbar-2 почему такой класс? Почему - 2 ?

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +          </ul>
Что это делает в навигации?

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +          <p>Интернет-магазин строительных материалов и инструментов для ремонта</p>
Не навигация

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +          </ul>
Давать номера классам плохая идея. Им нужно давать семантичесике названия. Что мне говорит номер 3  тут ?? Как я пойму в будущем разницу между navbar-3 и navbar-2 или navbar-1 ??

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +      <h1>Перфораторы</h1>
Согласен для каталога, это лучше h1 👍

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +        <h2>Каталог товаров интернет-магазина</h2><!--скрытый h2-->
Посмотри на тег `hgroup`

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +            <p><input type="range" min="0" max="100" step="1" value="75" /></p>
Зачем тут каждый инпут в p обернули?

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +              <input id="Bosh" type="checkbox" checked />
А где value & name у инпутов?

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +              <input id="rechargeable" type="radio" checked />
Пройди тренажер в академии по тому как правильно делать радиогруппы

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +              <input id="rechargeable" type="radio" checked />
https://up.htmlacademy.ru/htmlcss/31/module/2/item/6/14

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +        <div class="filter">
Класс фильтр, а написано сортировка)

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +                  <figcaption><!--Скрыт.Появляется при наведении на любой из элементов div class="product"-->
А для чего используют `figcaption ` ?

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +                <a href="product.html">Перфоратор BOSCH BFG 6000</a>
product.html у нас нет такой страницы - я бы ставил заглушки

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +                <del>30500 р.</del>
👍

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +                  </figcaption><!---->
`<!----> ` зачем эти коментарии, они же засоряют ?

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +           <p><img src="images/icons_svg/icon-checked.svg" alt="Товар добавлен" />Товар добавлен в корзину!</p>
Почему она контентная картинка?

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +         В ассортиментном ряду есть выбор «трехрежимников»: в одном устройстве будут совмещены отбойный молоток и ударная дрель.</p>
```suggestion
        <p>
        Перфоратор — универсальный строительный инструмент. Предназначен для сверления и долбления отверстий в кирпиче, бетоне и камне.<br />
         Существуют электромеханические и пневматические перфораторы. Современные модели могут выполнять функции дрели, шуруповерта и отбойного молотка. 
         В ассортиментном ряду есть выбор «трехрежимников»: в одном устройстве будут совмещены отбойный молоток и ударная дрель.
         </p>
```

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +        <section>
Почему section?

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +        <section>
Почему section?

2021-05-27 18:54 UTC, Shramkoweb commented on catalog.html
> +        <section>
Почему section?

2021-05-27 18:54 UTC, Shramkoweb commented on index.html
> +            <figcaption class="pagination">
figcaption - зачем он тут, что делает?

2021-05-27 18:54 UTC, Shramkoweb commented on index.html
> +          <a title="Логотип производителя LG"><!--если заглушка-->
А где href у этих ссылок?

2021-05-27 18:54 UTC, Shramkoweb commented on index.html
> +        Мы стараемся изо всех сил, чтобы сделать ваши покупки приятными.</p>
```suggestion
      <p>
      Хороший интернет-магазин отличается от плохого не только ценами!
        Мы стараемся изо всех сил, чтобы сделать ваши покупки приятными.
        </p>
```

2021-05-27 18:54 UTC, Shramkoweb commented on index.html
> +          </figcaption>
Вижу figcaption, а где сам контент для figure??

2021-05-27 18:54 UTC, Shramkoweb commented on index.html
> +        <!--<button type="button">Закрыть</button>-->
В ссылку нельзя пихать кнопку и наоборот

2021-05-27 18:54 UTC, Shramkoweb commented on index.html
> +      <button type="button">Заблудились? Напишите нам!</button>
Это ссылка

2021-05-27 18:54 UTC, Shramkoweb commented on index.html
> +        <li><a href="blanc.html">Доставка</a></li>
```suggestion
        <li><a href="blank.html">Доставка</a></li>
```

2021-05-28 17:14 UTC, Gerda0283 reviewed
Добрый день! Установила плагин. Вчера и сегодня пыталась найти ваши метки ошибок в коде. Но не нашла. Может ли такое быть, что код верный или я неправильно пользуюсь гитхаб и ошибки на самом деле есть?

2021-05-28 17:17 UTC, Gerda0283 commented on catalog.html
> +<!DOCTYPE html>
О, увидела предложения исправлений

2021-05-28 18:39 UTC, Gerda0283 commented on catalog.html
> +            <input type="submit" value="Искать"><!--Скрытая-->
Поменяла на более подходящее к макету решение:
        <div class="search"><!--Div присваиваем вид поля-->
          <form action="https://echo.htmlacademy.ru/courses" method="get">
            <input id="search" type="text" name="search" placeholder="Поиск:"><!--Поле со скрытыми бордерами-->
            <button type="submit"></button><!--Скрытая css кнопка с иконкой лупы. Местами с полем поменяется сиэсесиной-->
          </form>
        </div>

2021-05-28 18:41 UTC, Gerda0283 commented on catalog.html
> +          </ul>
После лекции про css поняла

2021-05-28 18:44 UTC, Gerda0283 commented on catalog.html
> +              <input id="rechargeable" type="radio" checked />
Проходила, сделаю ещё раз

2021-05-28 18:46 UTC, Gerda0283 commented on catalog.html
> +                <a href="product.html">Перфоратор BOSCH BFG 6000</a>
Поняла

2021-05-28 18:48 UTC, Gerda0283 commented on catalog.html
> +                  <figcaption><!--Скрыт.Появляется при наведении на любой из элементов div class="product"-->
Подпись. Она может отсутствовать, а так как наша подпись содержит кнопки, то она должна всегда присутствовать, поэтому figcaption не годиться, верно?

2021-05-28 18:49 UTC, Gerda0283 commented on catalog.html
> +                  </figcaption><!---->
Это привычка у меня такая вредная. Помечаю, где конец добавленного блока

2021-05-28 18:50 UTC, Gerda0283 commented on catalog.html
> +           <p><img src="images/icons_svg/icon-checked.svg" alt="Товар добавлен" />Товар добавлен в корзину!</p>
Поняла. Исправлю

2021-05-28 18:53 UTC, Gerda0283 commented on index.html
> +      <button type="button">Заблудились? Напишите нам!</button>
Спасибо, сначала так и хотела

2021-05-28 19:00 UTC, Gerda0283 commented on catalog.html
> +          <a class="bookmarks" href="blanc.html">Закладки:</a> <output for="bookmarks" name="result">0</output>
Я наверно его удалю, поскольку кнопкам в каталоге нельзя давать одинаковые id. Валидатор заругался. Появление количества нажатий можно скриптом задать

2021-05-28 19:01 UTC, Gerda0283 commented on catalog.html
> +        <div class="navbar-2">
вот с реализацией шапки в голове полная каша, но есть ещё альтернатива, которую надо попробовать.

2021-05-28 19:02 UTC, Gerda0283 commented on catalog.html
> +          </ul>
Поняла. Никуда не посылает, значит и не навигация.

2021-05-28 19:16 UTC, Gerda0283 commented on catalog.html
> +        <h2>Каталог товаров интернет-магазина</h2><!--скрытый h2-->
Мне идея понятна и приятна, но вот наткнулась на такую рекомендацию на вебреференс:
"Данный элемент исключён из спецификации W3C HTML5, но оставлен в спецификации WHATWG. Не рекомендуем его применять на рабочих сайтах, поскольку статус элемента точно не определён и его дальнейшая судьба не известна."
Но, почитав саму спецификацию W3C никаких противопоказаний не нашла. Попробую.

2021-05-28 19:20 UTC, Gerda0283 commented on index.html
> +          <a title="Логотип производителя LG"><!--если заглушка-->
Хотела с Вами посоветоваться. Ссылки ли это вообще?!

2021-05-29 17:10 UTC, Gerda0283 commented on catalog.html
> +        <section>
Можно и тег нав, но про него в спецификации написано можно но не нужно. Хотя он сюда подходит

2021-05-29 17:13 UTC, Gerda0283 commented on catalog.html
> +        <section>
зфменила на нав

2021-05-29 17:13 UTC, Gerda0283 commented on catalog.html
> +        <section>
заменила на нав

2021-05-29 18:45 UTC, Shramkoweb commented on catalog.html
> +          <a class="bookmarks" href="blanc.html">Закладки:</a> <output for="bookmarks" name="result">0</output>
Да и он не нужен тут - почитай документацию что делает этот тег. У него есть прям цель, а зачм он тут я не понял))

2021-05-29 18:46 UTC, Shramkoweb commented on catalog.html
> +        <h2>Каталог товаров интернет-магазина</h2><!--скрытый h2-->
вебреференс - просто сайт, я бы его читал но прверял все в документации)) Ты молодец

2021-05-29 18:47 UTC, Shramkoweb commented on catalog.html
> +                  <figcaption><!--Скрыт.Появляется при наведении на любой из элементов div class="product"-->
Ага

2021-05-29 18:47 UTC, Shramkoweb commented on catalog.html
> +                  </figcaption><!---->
Понял, ок это что то с php & WP?

2021-05-29 18:48 UTC, Shramkoweb commented on catalog.html
> +        <section>
Я бы взял просто `div`. Тебе по сути тут для дизайна надо разбить на блоки, и эти блоки не несут семантики - тут идельно подходит див

2021-05-29 18:48 UTC, Shramkoweb commented on catalog.html
> +        <section>
div

2021-05-29 18:48 UTC, Shramkoweb commented on catalog.html
> +        <section>
div ))

2021-05-29 18:48 UTC, Shramkoweb commented on index.html
> +          <a title="Логотип производителя LG"><!--если заглушка-->
да, ссылка на производителя.

2021-05-30 14:30 UTC, Gerda0283 commented on blanc.html
> +  </html>
done!

2021-05-30 14:37 UTC, Gerda0283 commented on catalog.html
> +        <h2>Каталог товаров интернет-магазина</h2><!--скрытый h2-->
У меня h1 над секциями а h2 h3 во внутренностях секций. И по логике они имено для внутренностей и модходят. Предлагаю пока так и оставить

2021-05-30 14:45 UTC, Gerda0283 commented on catalog.html
> +            <p><input type="range" min="0" max="100" step="1" value="75" /></p>
p поубирала везде (ведь если возле одних нет, то и остальные должны не иметь). Теперь думаю, как их в колонну лучше выстроить с помощью списков или сиэсесины.

2021-05-30 14:47 UTC, Gerda0283 commented on index.html
> +            <figcaption class="pagination">
Он тут по делу. Это не верно было ярлычёк NEW в него всовывать. Так получается разночтение.

2021-05-30 14:48 UTC, Gerda0283 commented on index.html
> +          </figcaption>
Исправила. Засунула его в подпись. Просто тупанула..

2021-05-30 16:17 UTC, Gerda0283 commented
Добрый вечер! Я конечно ещё "плаваю" в гитхабе "без акваланга", но вроде должна была обновить (с учётом изменений) данный пул реквест. Проверьте пожалуйста.

2021-05-31 16:49 UTC, Gerda0283 commented on catalog.html
> +                  </figcaption><!---->
Не. Фрилансю периодически с одним разработчиком. Делаю ему дизайн и вёрстку. Обходились пока без гита. Изменения помечаю коментами в коде, в действующих тоже делаю изменения и тоже пишу коменты - что сделано, где началось и где конец. В гите такая вещь лишняя.

2021-05-31 16:52 UTC, Gerda0283 commented on catalog.html
> +        <section>
Вы прям мысли читаете. Вроде так и сделала! Хотя у меня вот с "дивками" и вся проблема. Очень много их использовала. А теперь, пытаясь следовать симантике, не использую даже там, где нужно)))

2021-05-31 17:05 UTC, Gerda0283 commented on catalog.html
> +        <section>
Сделала

2021-05-31 17:06 UTC, Gerda0283 commented on catalog.html
> +        <section>
Сделала

2021-05-31 17:20 UTC, Gerda0283 commented on catalog.html
> +            <input type="submit" value="Искать"><!--Скрытая-->
Поменяла ещё раз. На не такое мудрёное)

2021-06-01 15:03 UTC, Shramkoweb approved these changes

2021-06-01 15:03 UTC, Shramkoweb commented on index.html
> +  <!--<p>Репозиторий создан для обучения на профессиональном онлайн‑курсе «<a href="https://htmlacademy.ru/intensive/htmlcss">HTML и CSS. Профессиональная вёрстка сайтов</a>».</p>-->
Можно убрать

2021-06-01 15:04 UTC, merged

2021-06-01 16:31 UTC, Gerda0283 commented on catalog.html
> +        <div class="navbar-2">
Хотя каша по мере дочитывания учебного материала таки рассеялась)))

2021-06-02 09:54 UTC, Gerda0283 commented on index.html
> +  <!--<p>Репозиторий создан для обучения на профессиональном онлайн‑курсе «<a href="https://htmlacademy.ru/intensive/htmlcss">HTML и CSS. Профессиональная вёрстка сайтов</a>».</p>-->
Поправила