Стилизация главной страницы
htmlacademy-htmlcss/841461-technomart-31 pull request #5
Opened 2021-06-22 00:23 UTC by Gerda0283

И не только). На футтере правда и конь не валялся.

2021-06-22 19:12 UTC, Shramkoweb requested changes

2021-06-22 19:12 UTC, Shramkoweb commented on css/style.css
> +  font-weight: 700;
У тебя что для 400, что для 700 тянет локально одни и те же шрифты. 
400 - ../fonts/ptsans.woff2
700 -../fonts/ptsans.woff2
Оба шрифта будут одинаковые

2021-06-22 19:12 UTC, Shramkoweb commented on css/style.css
> +       url("../fonts/cuprum.woff2") format("woff2"),
Аналогичн выше

2021-06-22 19:12 UTC, Shramkoweb commented on css/style.css
> +img {
https://codeguide.academy/html-css.html кидал в чат. Пофикси плз согласно гайду, кроме сортировки

2021-06-22 19:12 UTC, Shramkoweb commented on css/style.css
> +  height: 38px;
Убирай высоту для ссылок и кнопок. 

https://isqua.ru/blog/2016/06/19/crash-test-viorstki/

2021-06-22 19:12 UTC, Shramkoweb commented on css/style.css
> +.logo-img path {
Зачем прям path ?

2021-06-22 19:12 UTC, Shramkoweb commented on css/style.css
> +  height: 42px;
Убираем высоту фиксированиую.

2021-06-22 19:12 UTC, Shramkoweb commented on css/style.css
> +.phone-number > a {
Зачем тут такой селектор?

2021-06-22 19:12 UTC, Shramkoweb commented on css/style.css
> +.main-navigation ul li a {
Ой не - убирай такую вложеность. Зачем она?

2021-06-22 19:12 UTC, Shramkoweb commented on css/style.css
> +  height:261px
min-height

2021-06-22 19:12 UTC, Shramkoweb commented on index.html
> +            <img class="tm-img" src="images/producers/producer-hitachi.jpg" alt="Логотип производителя Hitachi" />
tm- ?? Что значит ??

2021-06-28 13:30 UTC, Gerda0283 commented on catalog.html
> +    <nav class="main-navigation container">
Думала над этим, но нет. Не подходит. У нас цвета через секцию меняются. Контейнер должен быть внутри секции, а секция меняет цвет.

2021-06-28 13:32 UTC, Gerda0283 commented on catalog.html
> +        <li class="addr-text">г. Санкт-Петербург, наб. Реки Карповки, 5 лит П</li>
Исправила на понятный address-text

2021-06-28 13:42 UTC, Gerda0283 commented on catalog.html
> +        <li class="mn-list-item"><a href="index.html">Главная</a></li>
.main-navigation ul li Можно вообще не называть, а задать вот так .main-navigation ul li (без классов)? (добавила классы к элементам списка чтобы соответствовать критериям, но логика в данном месте мне не нравится)
Cокращённо mn (main-navigation). Назвала дочерние элементы (li). Перенесла в каталог со страницы индекс  только на одну ссылку (ошибочно). Исправила, назвав все mn-list-item.

2021-06-28 13:43 UTC, Gerda0283 commented on catalog.html
> +        <li class="mn-list-item"><a href="blanc.html">Новости</a></li>
Может быть. Исправляю

2021-06-28 13:49 UTC, Gerda0283 commented on catalog.html
> +                  <div class="bar" style="width: 40%; margin-left: 10%;">
Я их потом обязательно уберу. Єто заготовка для фильтра бегунка между ценами. И подключения к нему скрипта. Подпишу коментами, что временно.

2021-06-28 13:52 UTC, Gerda0283 commented on catalog.html
> +                    <button class="toggle toggle-bar-min" style="left: 10%;"></button>
Не будет пустой, когда до неё дойду

2021-06-28 13:52 UTC, Gerda0283 commented on catalog.html
> +                    <button class="toggle toggle-bar-min" style="left: 10%;"></button>
Инлайн уберу, как только оформлю фильтр

2021-06-28 13:57 UTC, Gerda0283 commented on catalog.html
> +              <input type="number" min="0" value="0" />&mdash;
done!

2021-06-28 14:00 UTC, Gerda0283 commented on catalog.html
> +                <input class="filter-input-radio filter-input" type="radio" name="power-supply" value="Аккумуляторные" id="rechargeable">
Написала тогда правильным переводом: rechargeable and mains

2021-06-28 14:01 UTC, Gerda0283 commented on catalog.html
> +                <input class="filter-input-radio filter-input" type="radio" name="power-supply" value="Сетевые" id="mains">
Done!

2021-06-28 14:06 UTC, Gerda0283 commented on catalog.html
> +              <a class="product-link" title="Карта товара">Перфоратор BOSCH BFG 6000</a>
Убрала вообще. Не могу сейчас понять, что там нужно указать.

2021-06-28 14:07 UTC, Gerda0283 commented on catalog.html
> +              <h4 class="headline-inner visually-hidden">Перфоратор BOSCH BFG 6000</h4>
Логично, убираю

2021-06-28 14:12 UTC, Gerda0283 commented on catalog.html
> +            <a class="page-link visually-hidden" aria-disabled="true">Предидущая</a>
done!

2021-06-28 14:13 UTC, Gerda0283 commented on catalog.html
> +        <button type="button btn-tsf">Продолжить покупки</button>
transfer)))
Поняла, без сокращений)

2021-06-28 14:20 UTC, Gerda0283 commented on css/style.css
> +  font-weight: 700;
Это моя главная проблема. Прочиала по єтому поводу то что біло написано в учебнике. И поняла, что разной жирности подключать нельзя??? Или нужно с указанием жирности и наклона ??? Я лично думаю, что лучше подключить италик, жирный и жирный италик и указать им фонт вейты и стили италик, тогда будет отображаться. Но учебгик считает, что я не права или я его не правильно поняла?

2021-06-28 14:21 UTC, Gerda0283 commented on css/style.css
> +       url("../fonts/cuprum.woff2") format("woff2"),
Мне нужна консультация по этому поводу. Со шрифтами путаница

2021-06-28 18:58 UTC, Gerda0283 commented on css/style.css
> +img {
Хороший гайд, кучу ошибок нашла в сиэсесе, которые по невнимательности допустила. спасибо. Исравляю

2021-06-28 19:03 UTC, Gerda0283 commented on css/style.css
> +  height: 38px;
Убираю

2021-06-29 12:04 UTC, Gerda0283 commented on css/style.css
> +  height: 38px;
почистила

2021-06-29 12:05 UTC, Gerda0283 commented on css/style.css
> +.logo-img path {
done!

2021-06-29 12:07 UTC, Gerda0283 commented on css/style.css
> +  height: 42px;
done

2021-06-29 12:11 UTC, Gerda0283 commented on css/style.css
> +.phone-number > a {
.phone-number a {} Сделала вот так

2021-06-29 12:13 UTC, Gerda0283 commented on css/style.css
> +.main-navigation ul li a {
.mn-list-item a {
  color: var(--basic-white);
}
Сделала

2021-06-29 12:23 UTC, Gerda0283 commented on index.html
> +            <img class="tm-img" src="images/producers/producer-hitachi.jpg" alt="Логотип производителя Hitachi" />
Все сокращения поубирала

2021-06-29 12:24 UTC, Gerda0283 commented
Сейчас порешаю со шрифтами и скину на проверку

2021-06-29 13:34 UTC, Gerda0283 commented on catalog.html
> +        <li class="mn-list-item"><a href="index.html">Главная</a></li>
Убрала непонятніе сокращения

2021-06-29 13:35 UTC, Gerda0283 commented on css/style.css
> +  font-weight: 700;
Проблему поборола!!!!

2021-06-29 19:10 UTC, Shramkoweb commented on css/style.css
> +  font-weight: 700;
Можешь писать мне - если не получаеться что-то сделать)) НЕ стеснйся ))

2021-06-29 19:11 UTC, Shramkoweb approved these changes

2021-06-29 19:11 UTC, merged