Стилизация внутренней станицы
htmlacademy-htmlcss/841461-technomart-31 pull request #6
Opened 2021-07-03 08:46 UTC by Gerda0283

На стадии декорации хуверов и доступности

2021-07-03 13:53 UTC, Shramkoweb requested changes

2021-07-03 13:53 UTC, Shramkoweb commented on catalog.html
> +      </li><!--Заменить на иконку с svg-->
Уже же заменила - комментарий можно убирать?

2021-07-03 13:53 UTC, Shramkoweb commented on catalog.html
>        <!--скрытый h3-->
А почему 2 заголовка ?? Как пармер и скринридер поймет - это Интрументы или Каталог товаров интернет-магазина ?

Почитай про https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup если это группа заголовков

2021-07-03 13:53 UTC, Shramkoweb commented on catalog.html
> +            <li><button class="current" type="button">по цене</button></li>
Похоже на радио группу?

2021-07-03 13:53 UTC, Shramkoweb commented on css/style.css
> +  font-weight: 700;
👍

2021-07-03 13:53 UTC, Shramkoweb commented on css/style.css
> +  background: url(../images/icons_svg/icon-angle.svg) no-repeat;
Есть критерий по единообразию кода. Ты тут пишешь сокращенную версию, а дальше разбираешь на свойства отдельно. 
Пиши единообразно везде. 

` ``
background-image: url(../images/icons_svg/icon-bookmarks.svg);
background-repeat: no-repeat;
background-position: 0 0;
```

2021-07-03 13:53 UTC, Shramkoweb commented on index.html
> +            <button class="slide-btn slider-control-left" type="button" aria-label="Назад" disabled></button>
👍  молодец за доступность)

2021-07-03 20:30 UTC, Gerda0283 commented on catalog.html
> +      </li><!--Заменить на иконку с svg-->
done

2021-07-03 21:02 UTC, Gerda0283 commented on catalog.html
>        <!--скрытый h3-->
Удалю h3 и скрытые h4 в перечне товаров. Будет скрытый h2 в секции над товарами и второй h2 открытый в секции с описанием

2021-07-03 21:02 UTC, Gerda0283 commented on catalog.html
>        <!--скрытый h3-->
Группировать заголовки не могу, они у меня между секциями

2021-07-04 07:34 UTC, Gerda0283 commented on css/style.css
> +  background: url(../images/icons_svg/icon-angle.svg) no-repeat;
done

2021-07-04 07:34 UTC, Gerda0283 commented on css/style.css
> +  font-weight: 700;
Я тут где-то в каком-то знаке ошибрась и из-за этого жирный птсанс не рендериться. Если заметите ошибку раньше меня, маякните плиз.

2021-07-04 07:34 UTC, Gerda0283 commented on catalog.html
> +            <li><button class="current" type="button">по цене</button></li>
Done

2021-07-06 15:56 UTC, Shramkoweb approved these changes

2021-07-06 15:56 UTC, merged