Сетка на гридах для внутренней страницы
htmlacademy-htmlcss/841461-technomart-31 pull request #8
Opened 2021-07-09 15:13 UTC by Gerda0283

Не работает шрифт PT Sans  с жирностью 700. Может где-то ошиблась в одной букве  / знаке / пробеле. Не могу найти. Проверила на доступность и переполнение.  Скрипт сделала пока только на форму обратной связи (кнопка под картой. Если где заметите какой-то баг, маякните пожалуйста

2021-07-10 20:30 UTC, Shramkoweb commented
@Gerda0283 судя по всему ты совсем PT Sans  не грузишь. 
![image](https://user-images.githubusercontent.com/42001531/125175740-ba502e80-e1d6-11eb-97fc-dffcbcff5bd5.png)

2021-07-10 20:39 UTC, Shramkoweb requested changes

2021-07-10 20:39 UTC, Shramkoweb commented on css/style.css
> +  width: 218px;
Пройдет переполнение ?

2021-07-10 20:39 UTC, Shramkoweb commented on css/style.css
> +  width: 135px;
Переполнение будет ок?

2021-07-10 20:39 UTC, Shramkoweb commented on js/forms.js
> +}
Форматирование - отступы

2021-07-10 20:39 UTC, Shramkoweb commented on js/forms.js
> +popup.classList.remove("modal-error");
```suggestion
popup.classList.remove("modal-feedback-show", "modal-error");
```

2021-07-10 20:39 UTC, Shramkoweb commented on js/forms.js
> +popup.classList.remove("modal-error");
Можно к одному елементу через запятую добавлять/удалять классы

2021-07-12 18:32 UTC, Gerda0283 commented on css/style.css
> +  width: 218px;
Спасибо, теперь выдержит и переполнением кнопками и переполнением самой кнопки

2021-07-12 18:32 UTC, Gerda0283 commented on css/style.css
> +  width: 135px;
пофиксила вместе кнопкой

2021-07-12 19:04 UTC, Gerda0283 commented on js/forms.js
> +}
Вы имеете в виду от скобок , в которых есть название селектора?

2021-07-12 19:30 UTC, Gerda0283 commented on css/style.css
> +  width: 218px;
Не работает фокус не на имени

2021-07-12 19:30 UTC, Gerda0283 commented on css/style.css
> +  width: 218px;
Почему, не могу понять

2021-07-13 16:10 UTC, Shramkoweb commented on css/style.css
> +  width: 218px;
Давай потом решим - это доп кр итерий. Надо успеть что-то отправить))

2021-07-13 16:10 UTC, Shramkoweb approved these changes

2021-07-13 16:10 UTC, merged